require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ErynTemplate' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ErynTemplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '~> 2.5.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'ErynTemplate-tvOS' do
  # Pods for ErynTemplate-tvOS

  target 'ErynTemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
